### ISSUE TITLE
adopt Probot Settings for new and existing repos

### ISSUE THREAD

**Issue by ahmadnassri** [nodejs/admin#303]
[Probot](https://probot.github.io/) is a great free automation utility for GitHub, [Probot Settings](https://probot.github.io/apps/settings/) is an app that syncs repository settings defined in `.github/settings.yml` to GitHub API, enabling repositories to version control their own settings and allow Pull Requests for them.

This allows controlling ALL aspects of a github repository, from name & description, to labels & collaborators, and even branch protection configuration.

> #### Live Example
> 
> I personally use this for my own accounts and for work _(`github.com/telus`)_ this allows me and my team mates to provision new repositories with some configuration already scaffolded.
> 
> here's my root configuration: https://github.com/ahmadnassri/.github
> 
> here's one of my repos that `_extends`: the root configuration: https://github.com/ahmadnassri/node-api-problem/blob/master/.github/settings.yml

## Node.js Useage

I propose creating a `.github` repository with some basic root configuration, here is my reccomendation:

```yaml
repository:
  topics: nodejs
  homepage: https://nodejs.org/
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true

labels:
  - name: Good First Issue
    description: Good for newcomers
    color: 7057ff
```

Repos then would add `.github/settings.yml`:

```yaml
_extends: .github

repository:
  name: my-repo-name
  description: meaningful description
  topics: nodejs, is, awesome
```

**Notes:**
- There should be a good existing starter example for labels in Node projects here, so lets pick from those. Having labels configured and available from the start of a repo is crucial for open collaboration.

- Prefer that we include _branch protection_ configuration, however that might prove controversial.

- Probot Settings support extending templates, so we can have purpose based starter templates:
  ```yaml
  # a template for working groups repos
  _extends: .github:group.yml

  # a template for code repos
  _extends: .github:code.yml

  # a template for anything
  _extends: .github:something-special.yml
  ```

### Steps needed

- a member with `owner` GitHub privileges installs Probot from: https://github.com/apps/settings 
- a repo named `.github` is created with a starting default template _(I can start that once we have sign off)_
- teams and projects can start adopting into their own repos by including a `.github/settings.yml`
