### ISSUE TITLE
Install semantic-pull-requests for nodejs/examples

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#497]
I'd like to request that the Semantic Pull Request [GitHub App](https://github.com/apps/semantic-pull-requests) ([source](https://github.com/zeke/semantic-pull-requests)) be added for [nodejs/examples](https://github.com/nodejs/examples).

The GitHub App is built by a long-time Node.js community member and current Node.js project member (i18n) @zeke.

I've found it useful in helping create consistent and understandable commit logs in projects, especially as they grow. It seems like an ideal tool to use for nodejs/examples because it helps enforce a consistent commit structure, which will helpfully help reduce confusion for those who are trying to learn  💚

**Comment by zeke** [comment]
👋 happy to help support this if it's what the community wants.

For the uninitiated, I recorded a demo that covers how to set up and use `semantic-release` and the Semantic Pull Requests GitHub app:

- Tweet: https://twitter.com/zeke/status/1240717367501414400
- Video: https://www.youtube.com/watch?v=rCXq86FOlzQ&feature=emb_logo
- Repo: https://github.com/zeke/semantic-release-with-github-actions

**Comment by bnb** [comment]
Per the new bot guidelines, here are the permissions the bot requires:

![image](https://user-images.githubusercontent.com/502396/89933271-d0c3c380-dbdc-11ea-8193-74192663c7c7.png)

also, per the same policy need 2 +1s from both @nodejs/tsc and @nodejs/community-committee

**Comment by mmarchini** [comment]
+1

out of curiosity, any reasons to have this as a GitHub App instead of an Action (besides it already being implemented as an App)?

**Comment by bnb** [comment]
That would be a good question for @zeke 👍🏻

**Comment by zeke** [comment]
Borrowing from https://github.com/zeke/semantic-pull-requests/issues/90#issuecomment-671442448

> FWIW, an app works out much better for multiple projects. It's faster than GH actions, doesn't eat up actions runtime quota, easier to configure and so on. There's more you can do with GH actions but doing so again and again across projects becomes tedious after a while.

There is at least one GitHub Action with similar functionality: https://github.com/amannn/action-semantic-pull-request -- but last I checked it still had an issue with surfacing multiple checks on a single PR: https://github.com/amannn/action-semantic-pull-request/issues/5

On a personal note, I would love to see users gravitate toward Actions for validating their semantic pull requests, because maintaining the semantic-pull-requests GitHub App has required a lot of my attention. See https://github.com/zeke/semantic-pull-requests/issues/90 -- that said, I will continue to support the app until a suitable Actions alternative becomes available.

**Comment by mmarchini** [comment]
what a weird issue :O

Both the Action and the App only check if commits are following https://conventionalcommits.org, right? If so I've been doing that on some projects with the following Action:

```yaml
---
name: Conventional Commit Linter
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  name: Lint
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: v12
    - run: npm install
    - run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}
```

I'm probably missing some edge cases or some use cases though.
