### ISSUE TITLE
Enable github actions can create pull requests

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/admin#911]
I noticed that after the transition to enterprise org, the ability for github actions to create PR has been revoked.
On amaro it fails:
<img width="1007" alt="Screenshot 2024-08-19 at 12 49 48" src="https://github.com/user-attachments/assets/afc33e6c-78b1-45aa-aa73-234625e10d2d">

If I try to change at repo level the checkbox is disabled.
<img width="871" alt="Screenshot 2024-08-19 at 12 46 39" src="https://github.com/user-attachments/assets/2f9d4cec-bfd3-48f8-946d-6887336035aa">

I think this has to be changed at organization level https://github.com/enterprises/nodejs/settings/actions

ping @nodejs/tsc

**Comment by legendecas** [comment]
Would you mind trying the following settings in the github action yaml ([doc](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token))?:

```yaml
jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
```
